// Bloom-lCMSの `menu` / `recruit` API(公開分のみ)を取得し、
// src/lib/menu.generated.ts / src/lib/recruit.generated.ts を再生成する。
// npm run dev / npm run build の pre フックとして自動実行される(npm run sync:menu で単独実行も可)。
// 必要な環境変数: BLOOM_API_URL / BLOOM_API_KEY(.env.local または実行環境の環境変数)
// 採用は「公開中の職種が0件=募集していない」と解釈し、サイト側が採用ページごと非表示にする。
import { readFile, writeFile, mkdir, access } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { createHash } from "node:crypto";

// Vercel等ではプラットフォームが直接 process.env に注入するため、
// .env.local が存在する場合のみ、まだ未設定のキーを補う(既存の環境変数は上書きしない)
const loadDotEnvLocal = async () => {
  try {
    const raw = await readFile(new URL("../.env.local", import.meta.url), "utf8");
    for (const line of raw.split("\n")) {
      const m = /^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/.exec(line);
      if (!m) continue;
      const [, key, value] = m;
      if (process.env[key] === undefined) {
        process.env[key] = value.replace(/^["']|["']$/g, "");
      }
    }
  } catch {
    // .env.local が無ければ何もしない(本番はプラットフォーム側の環境変数を使う)
  }
};

await loadDotEnvLocal();

const API_URL = process.env.BLOOM_API_URL;
const API_KEY = process.env.BLOOM_API_KEY;

if (!API_URL || !API_KEY) {
  console.error(
    "[sync-menu] BLOOM_API_URL / BLOOM_API_KEY が未設定です。.env.local を確認してください(取得元: Bloom-lCMS管理画面の「HP連携設定」)。",
  );
  process.exit(1);
}

const CATEGORIES = ["lunch", "dinner", "course", "drink"];

const res = await fetch(`${API_URL}/api/v1/menu?limit=100`, {
  headers: { "X-MICROCMS-API-KEY": API_KEY },
});
if (!res.ok) {
  console.error(`[sync-menu] 配信APIエラー: HTTP ${res.status}`);
  process.exit(1);
}
const { contents } = await res.json();

// ---- サムネイル生成 ----
// TOP の料理ビートは CMS の写真を 32〜46px の角丸サムネイルでしか使わないのに、
// 原寸(300〜400KB の JPEG)をそのまま背景画像にしていた。ビルド時に 128px
// (Retina で 2.8 倍)の WebP へ縮めて public/menu-thumbs/ に置き、
// `thumb` として別フィールドで渡す(`img` は原寸 URL のまま残す)。
// 取得・変換に失敗した品は thumb を持たず、サイト側が img へフォールバックする。
const THUMB_DIR = new URL("../public/menu-thumbs/", import.meta.url);
const THUMB_SIZE = 128;
let sharp = null;
try {
  sharp = (await import("sharp")).default;
} catch {
  console.warn("[sync-menu] sharp が無いためサムネイル生成をスキップ(原寸 URL を使用)");
}
const makeThumb = async (url) => {
  if (!sharp || !url) return undefined;
  const name = createHash("sha1").update(url).digest("hex").slice(0, 16) + ".webp";
  const file = new URL(name, THUMB_DIR);
  const publicPath = `/menu-thumbs/${name}`;
  try {
    await access(file);
    return publicPath; // 生成済み(URL が変われば名前も変わる)
  } catch {
    /* 未生成 */
  }
  try {
    const r = await fetch(url);
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    const buf = Buffer.from(await r.arrayBuffer());
    await mkdir(THUMB_DIR, { recursive: true });
    await sharp(buf)
      .rotate()
      .resize(THUMB_SIZE, THUMB_SIZE, { fit: "cover", position: "centre" })
      .webp({ quality: 74 })
      .toFile(fileURLToPath(file));
    return publicPath;
  } catch (e) {
    console.warn(`[sync-menu] サムネイル生成に失敗(原寸を使用): ${url} — ${e.message}`);
    return undefined;
  }
};

const grouped = Object.fromEntries(CATEGORIES.map((c) => [c, []]));
for (const item of contents) {
  if (!CATEGORIES.includes(item.category)) {
    console.warn(`[sync-menu] 未知のcategory「${item.category}」をスキップ(id=${item.id})`);
    continue;
  }
  const spicy = [1, 2, 3].includes(item.spicy) ? item.spicy : undefined;
  // 画像は管理画面の入れ方で「URL文字列」と「{url, alt} オブジェクト」が混在する。
  // サイト側は文字列(URL)の単一形に正規化する
  const img = typeof item.img === "string" ? item.img : item.img?.url;
  const thumb = await makeThumb(img);
  grouped[item.category].push({
    order: typeof item.order === "number" ? item.order : 999,
    entry: {
      name: item.title,
      price: item.price,
      // 飲み物のみ使用: BEER / SHOCHU / … の章分け(src/lib/menu.ts の DRINK_GROUPS が見出しの出典)
      ...(item.group ? { group: item.group } : {}),
      ...(item.desc ? { desc: item.desc } : {}),
      ...(item.signature ? { signature: true } : {}),
      ...(item.recommended ? { recommended: true } : {}),
      ...(spicy !== undefined ? { spicy } : {}),
      ...(img ? { img } : {}),
      ...(thumb ? { thumb } : {}),
    },
  });
}
for (const c of CATEGORIES) grouped[c].sort((a, b) => a.order - b.order);

const body = CATEGORIES.map(
  (c) => `  ${c}: [\n${grouped[c].map((x) => "    " + JSON.stringify(x.entry)).join(",\n")}\n  ],`,
).join("\n");

const out = `// AUTO-GENERATED by scripts/sync-menu.mjs — 直接編集しないこと(次回同期で上書きされる)。
// 出典: Bloom-lCMS \`menu\` API(公開品目のみ)。再生成: npm run sync:menu
import type { MenuItem } from "./menu";

export const CMS_MENU_ITEMS: Record<"lunch" | "dinner" | "course" | "drink", MenuItem[]> = {
${body}
};
`;

await writeFile(fileURLToPath(new URL("../src/lib/menu.generated.ts", import.meta.url)), out, "utf8");

const total = CATEGORIES.reduce((n, c) => n + grouped[c].length, 0);
console.log(
  `[sync-menu] ${total}件を同期しました (${CATEGORIES.map((c) => `${c}:${grouped[c].length}`).join(" ")})`,
);

// ---- お知らせ(notice) ----
// 掲載期間の判定はビルド時ではなく閲覧時(ブラウザ)に行う。
// ビルド時に判定すると、期限が過ぎても次のビルドまで古い告知が残ってしまうため
const noticeRes = await fetch(`${API_URL}/api/v1/notice?limit=100`, {
  headers: { "X-MICROCMS-API-KEY": API_KEY },
});
let notices = [];
if (noticeRes.ok) {
  const { contents: noticeContents } = await noticeRes.json();
  notices = noticeContents.map((item) => ({
    id: item.id,
    title: item.title,
    ...(item.body ? { body: item.body } : {}),
    level: item.level === "alert" ? "alert" : "info",
    ...(item.startAt ? { startAt: item.startAt } : {}),
    ...(item.endAt ? { endAt: item.endAt } : {}),
  }));
} else if (noticeRes.status !== 404) {
  console.error(`[sync-menu] notice配信APIエラー: HTTP ${noticeRes.status}`);
  process.exit(1);
}

const noticeOut = `// AUTO-GENERATED by scripts/sync-menu.mjs — 直接編集しないこと(次回同期で上書きされる)。
// 出典: Bloom-lCMS \`notice\` API(公開分のみ)。掲載期間の判定は閲覧時にブラウザ側で行う。
import type { Notice } from "./notice";

export const CMS_NOTICES: Notice[] = [
${notices.map((n) => "  " + JSON.stringify(n) + ",").join("\n")}
];
`;

await writeFile(
  fileURLToPath(new URL("../src/lib/notice.generated.ts", import.meta.url)),
  noticeOut,
  "utf8",
);
console.log(`[sync-menu] お知らせ: ${notices.length}件(掲載期間は閲覧時に判定)`);

// ---- 営業カレンダー(calendar) ----
// 「通常と違う日」だけが記事として入っている(1日=1記事)。
// 過去日の除外はビルド時ではなく閲覧時にブラウザで行う(お知らせと同じ理由)
const calRes = await fetch(`${API_URL}/api/v1/calendar?limit=100`, {
  headers: { "X-MICROCMS-API-KEY": API_KEY },
});
let calDays = [];
if (calRes.ok) {
  const { contents: calContents } = await calRes.json();
  calDays = calContents
    .filter((c) => typeof c.date === "string" && /^\d{4}-\d{2}-\d{2}$/.test(c.date))
    .map((c) => ({
      date: c.date,
      state: ["closed", "lunch", "dinner", "custom"].includes(c.state) ? c.state : "closed",
      ...(c.open ? { open: c.open } : {}),
      ...(c.close ? { close: c.close } : {}),
      ...(c.note ? { note: c.note } : {}),
    }))
    .sort((a, b) => a.date.localeCompare(b.date));
} else if (calRes.status !== 404) {
  console.error(`[sync-menu] calendar配信APIエラー: HTTP ${calRes.status}`);
  process.exit(1);
}

const calOut = `// AUTO-GENERATED by scripts/sync-menu.mjs — 直接編集しないこと(次回同期で上書きされる)。
// 出典: Bloom-lCMS \`calendar\` API(公開分のみ)。過去日の除外は閲覧時にブラウザ側で行う。
import type { CalendarDay } from "./calendar";

export const CMS_CALENDAR_DAYS: CalendarDay[] = [
${calDays.map((d) => "  " + JSON.stringify(d) + ",").join("\n")}
];
`;

await writeFile(
  fileURLToPath(new URL("../src/lib/calendar.generated.ts", import.meta.url)),
  calOut,
  "utf8",
);
console.log(`[sync-menu] 営業カレンダー: ${calDays.length}件の例外日`);

// ---- 採用募集(recruit) ----
// 404=テナントに recruit API が未作成(採用機能を使っていない)なので「募集なし」として扱う。
// それ以外のエラーはビルドを止める(中途半端な生成物で公開しない)
const recruitRes = await fetch(`${API_URL}/api/v1/recruit?limit=100`, {
  headers: { "X-MICROCMS-API-KEY": API_KEY },
});
let positions = [];
if (recruitRes.ok) {
  const { contents: recruitContents } = await recruitRes.json();
  positions = recruitContents
    .map((item) => ({
      order: typeof item.order === "number" ? item.order : 999,
      entry: { title: item.title, text: item.desc ?? "" },
    }))
    .sort((a, b) => a.order - b.order)
    .map((x) => x.entry);
} else if (recruitRes.status !== 404) {
  console.error(`[sync-menu] recruit配信APIエラー: HTTP ${recruitRes.status}`);
  process.exit(1);
}

const recruitOut = `// AUTO-GENERATED by scripts/sync-menu.mjs — 直接編集しないこと(次回同期で上書きされる)。
// 出典: Bloom-lCMS \`recruit\` API(公開職種のみ)。0件=募集していない(採用ページ非表示)。
import type { RecruitPosition } from "./recruit";

export const CMS_RECRUIT_POSITIONS: RecruitPosition[] = [
${positions.map((p) => "  " + JSON.stringify(p) + ",").join("\n")}
];
`;

await writeFile(
  fileURLToPath(new URL("../src/lib/recruit.generated.ts", import.meta.url)),
  recruitOut,
  "utf8",
);
console.log(`[sync-menu] 採用募集: ${positions.length}職種(0件なら採用ページ非表示)`);
