// Bloom-lCMSの `menu` / `recruit` API(公開分のみ)を取得し、
// src/lib/menu.generated.ts / src/lib/recruit.generated.ts を再生成する。
// npm run dev / npm run build の pre フックとして自動実行される(npm run sync:menu で単独実行も可)。
// 必要な環境変数: BLOOM_API_URL / BLOOM_API_KEY(.env.local または実行環境の環境変数)
// 採用は「公開中の職種が0件=募集していない」と解釈し、サイト側が採用ページごと非表示にする。
import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";

// Vercel等ではプラットフォームが直接 process.env に注入するため、
// .env.local が存在する場合のみ、まだ未設定のキーを補う(既存の環境変数は上書きしない)
const loadDotEnvLocal = async () => {
  try {
    const raw = await readFile(new URL("../.env.local", import.meta.url), "utf8");
    for (const line of raw.split("\n")) {
      const m = /^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/.exec(line);
      if (!m) continue;
      const [, key, value] = m;
      if (process.env[key] === undefined) {
        process.env[key] = value.replace(/^["']|["']$/g, "");
      }
    }
  } catch {
    // .env.local が無ければ何もしない(本番はプラットフォーム側の環境変数を使う)
  }
};

await loadDotEnvLocal();

const API_URL = process.env.BLOOM_API_URL;
const API_KEY = process.env.BLOOM_API_KEY;

if (!API_URL || !API_KEY) {
  console.error(
    "[sync-menu] BLOOM_API_URL / BLOOM_API_KEY が未設定です。.env.local を確認してください(取得元: Bloom-lCMS管理画面の「HP連携設定」)。",
  );
  process.exit(1);
}

const CATEGORIES = ["lunch", "dinner", "course", "drink"];

const res = await fetch(`${API_URL}/api/v1/menu?limit=100`, {
  headers: { "X-MICROCMS-API-KEY": API_KEY },
});
if (!res.ok) {
  console.error(`[sync-menu] 配信APIエラー: HTTP ${res.status}`);
  process.exit(1);
}
const { contents } = await res.json();

const grouped = Object.fromEntries(CATEGORIES.map((c) => [c, []]));
for (const item of contents) {
  if (!CATEGORIES.includes(item.category)) {
    console.warn(`[sync-menu] 未知のcategory「${item.category}」をスキップ(id=${item.id})`);
    continue;
  }
  const spicy = [1, 2, 3].includes(item.spicy) ? item.spicy : undefined;
  grouped[item.category].push({
    order: typeof item.order === "number" ? item.order : 999,
    entry: {
      name: item.title,
      price: item.price,
      ...(item.desc ? { desc: item.desc } : {}),
      ...(item.signature ? { signature: true } : {}),
      ...(item.recommended ? { recommended: true } : {}),
      ...(spicy !== undefined ? { spicy } : {}),
      ...(item.img ? { img: item.img } : {}),
    },
  });
}
for (const c of CATEGORIES) grouped[c].sort((a, b) => a.order - b.order);

const body = CATEGORIES.map(
  (c) => `  ${c}: [\n${grouped[c].map((x) => "    " + JSON.stringify(x.entry)).join(",\n")}\n  ],`,
).join("\n");

const out = `// AUTO-GENERATED by scripts/sync-menu.mjs — 直接編集しないこと(次回同期で上書きされる)。
// 出典: Bloom-lCMS \`menu\` API(公開品目のみ)。再生成: npm run sync:menu
import type { MenuItem } from "./menu";

export const CMS_MENU_ITEMS: Record<"lunch" | "dinner" | "course" | "drink", MenuItem[]> = {
${body}
};
`;

await writeFile(fileURLToPath(new URL("../src/lib/menu.generated.ts", import.meta.url)), out, "utf8");

const total = CATEGORIES.reduce((n, c) => n + grouped[c].length, 0);
console.log(
  `[sync-menu] ${total}件を同期しました (${CATEGORIES.map((c) => `${c}:${grouped[c].length}`).join(" ")})`,
);

// ---- 採用募集(recruit) ----
// 404=テナントに recruit API が未作成(採用機能を使っていない)なので「募集なし」として扱う。
// それ以外のエラーはビルドを止める(中途半端な生成物で公開しない)
const recruitRes = await fetch(`${API_URL}/api/v1/recruit?limit=100`, {
  headers: { "X-MICROCMS-API-KEY": API_KEY },
});
let positions = [];
if (recruitRes.ok) {
  const { contents: recruitContents } = await recruitRes.json();
  positions = recruitContents
    .map((item) => ({
      order: typeof item.order === "number" ? item.order : 999,
      entry: { title: item.title, text: item.desc ?? "" },
    }))
    .sort((a, b) => a.order - b.order)
    .map((x) => x.entry);
} else if (recruitRes.status !== 404) {
  console.error(`[sync-menu] recruit配信APIエラー: HTTP ${recruitRes.status}`);
  process.exit(1);
}

const recruitOut = `// AUTO-GENERATED by scripts/sync-menu.mjs — 直接編集しないこと(次回同期で上書きされる)。
// 出典: Bloom-lCMS \`recruit\` API(公開職種のみ)。0件=募集していない(採用ページ非表示)。
import type { RecruitPosition } from "./recruit";

export const CMS_RECRUIT_POSITIONS: RecruitPosition[] = [
${positions.map((p) => "  " + JSON.stringify(p) + ",").join("\n")}
];
`;

await writeFile(
  fileURLToPath(new URL("../src/lib/recruit.generated.ts", import.meta.url)),
  recruitOut,
  "utf8",
);
console.log(`[sync-menu] 採用募集: ${positions.length}職種(0件なら採用ページ非表示)`);
